task: "seephys_pro_level2_testmini"
dataset_kwargs:
  token: True
  data_files: "data/seephys_pro/level2_testmini-00000-of-00001.parquet"
test_split: train
include: _default_template_seephys_pro.yaml
